### ISSUE TITLE
Registration Flow Discussion

### ISSUE THREAD

**Issue by dax0** [hindsight-io/connect#12]

**Comment by dax0** [comment]
Currently when a user signs up they are a standard vanilla user.  Their profile does not show up in search results until we manually flag people as advisers.  What I was thinking was including a button in a user's profile page that says request to be adviser and we can go manually approve them for now since the scale isn't too much to handle.

In the future this can be a little more automated by automatically sending them email verification when they add a school on their timeline and show in parentheses that it's (unverified) until they verify it.  However there's going to be situations where people just don't have access to certain emails for undergrad if it was too far back so there will always be some manual approval.  I still don't think we'll hit a scale of advisers signing up that we can't automate that.

**Comment by dax0** [comment]
@julioreynaga @Mukund91

**Comment by devanshah1991** [comment]
As discussed per the phone call. Users and advisors will sign up the same way. Then, on the main profile, there will be a clearly denoted, sign-up as an advisor button. They'll put in their current edu email, which we will verify by sending a link to their emails. No need to verify previous institutions (that'll be impossible via email since you usually don't have access to prior institutions). Just need to verify the email address of the institution they give
